name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

cache-mode: none

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # pin@v1.321.0
        with:
          bundler-cache: false

      - name: install dependencies
        run: |
          bundle config set --local path "$PWD/vendor/bundle"
          bundle config set --local deployment true
          bundle install --jobs 4

      - name: lint
        run: bundle exec rubocop -c .rubocop.yml lib/ spec/
