name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@3783f195e29b74ae398d7caca108814bbafde90e # pin@v1.180.1
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test -k
