name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@c04af2bb7258bb6a03df1d3c1865998ac9390972 # pin@v1.194.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test -k
